/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoriosemana8;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

   
/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

   
     private Usuario usuarioIniciado;
    private Rank ranking;
    private Usuario[] usuarios;

    public MenuPrincipal(Usuario usuarioLogueado, Rank ranking, Usuario[] usuarios) {
        this.usuarioIniciado = usuarioLogueado;
        this.ranking = ranking;
        this.usuarios = usuarios;
        initComponents();
    }

    private void initComponents() {
        JButton botonJugar = new JButton("Jugar X-O");
        JButton botonRanking = new JButton("Ver Ranking");
        JButton botonCerrarSesion = new JButton("Cerrar Sesión");

        botonJugar.addActionListener(e -> jugarXO());
        botonRanking.addActionListener(e -> verRanking());
        botonCerrarSesion.addActionListener(e -> cerrarSesion());

        JPanel panel = new JPanel();
        panel.add(botonJugar);
        panel.add(botonRanking);
        panel.add(botonCerrarSesion);

        setTitle("Menú Principal");
        add(panel);
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    private void jugarXO() {
        String usernameJugador2 = JOptionPane.showInputDialog(this, "Ingrese el username del Jugador 2:");

        Usuario jugador2 = null;
        for (Usuario usuario : usuarios) {
            if (usuario != null && usuario.getUsername().equals(usernameJugador2)) {
                jugador2 = usuario;
                break;
            }
        }

        if (jugador2 == null) {
            JOptionPane.showMessageDialog(this, "Jugador no encontrado.");
            return;
        }

        new juego_Brayan(usuarioIniciado, jugador2, ranking).setVisible(true);
        this.dispose();
    }

    private void verRanking() {
        JOptionPane.showMessageDialog(this, ranking.mostrarRank());
    }

    private void cerrarSesion() {
        new MenuInicio().setVisible(true);
        this.dispose();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

